Fix linter warning (#547)
Error: 'c' is declared but its value is never read.

We fix this by not destructuring the context parameter. We could have instead prefixed it with an underscore, but since the purpose of this document is to remain simple and easy to consume, we preferred this approach.